export const SET_ACCEPTED_UPLOAD_FILES = 'SET_ACCEPTED_UPLOAD_FILES';
export const REMOVE_ACCEPTED_UPLOAD_FILES = 'REMOVE_ACCEPTED_UPLOAD_FILES';

export const SET_NEW_NOTEBOOK_TITLE = 'SET_NEW_NOTEBOOK_TITLE';