-- MySQL Script generated by MySQL Workbench
-- Fri Mar 12 16:22:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pigments
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pigments
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pigments` DEFAULT CHARACTER SET utf8 ;
USE `pigments` ;

-- -----------------------------------------------------
-- Table `pigments`.`notebook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pigments`.`notebook` (
  `notebook_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `recipe_amount` INT NULL,
  PRIMARY KEY (`notebook_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pigments`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pigments`.`recipe` (
  `recipe_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `year` INT NULL,
  `image_url` LONGTEXT NULL,
  `label_status` VARCHAR(45) NULL,
  `notebook_id` INT NOT NULL,
  PRIMARY KEY (`recipe_id`, `notebook_id`),
  INDEX `fk_recipe_notebook_idx` (`notebook_id` ASC),
  CONSTRAINT `fk_recipe_notebook`
    FOREIGN KEY (`notebook_id`)
    REFERENCES `pigments`.`notebook` (`notebook_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pigments`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pigments`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` LONGTEXT NULL,
  `color` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pigments`.`translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pigments`.`translation` (
  `translation_id` INT NOT NULL AUTO_INCREMENT,
  `xmin` FLOAT NULL,
  `xmax` FLOAT NULL,
  `ymin` FLOAT NULL,
  `ymax` FLOAT NULL,
  `type` VARCHAR(45) NULL,
  `localisation_source` VARCHAR(45) NULL,
  `localisation_status` VARCHAR(45) NULL,
  `translation_text` LONGTEXT NULL,
  `translation_parent_id` VARCHAR(45) NULL,
  `translation_source` VARCHAR(45) NULL,
  `translation_status` VARCHAR(45) NULL,
  `recipe_id` INT NOT NULL,
  `notebook_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`translation_id`, `recipe_id`, `notebook_id`, `category_id`),
  INDEX `fk_translation_recipe1_idx` (`recipe_id` ASC, `notebook_id` ASC),
  INDEX `fk_translation_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_translation_recipe1`
    FOREIGN KEY (`recipe_id` , `notebook_id`)
    REFERENCES `pigments`.`recipe` (`recipe_id` , `notebook_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_translation_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `pigments`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
